### ISSUE TITLE
Invalid value in parameters file causes hard-to-read error

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-batch-cli-extensions#18]
1. Create a job template with an **int** parameter.
2. Create a parameters file that sets this parameter to "weeble".
3. Run `az batch job create` with this template and parameters file.

Expected result: the command fails with a message such as "ERROR: Invalid value for <parameter-name>: 'weeble' is not an int"

Actual result: the command fails with the following error message:

```
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\azure\cli\command_modules\batch_extensions\_template_utils.py", line 86, in _validate_int
    value = int(value)
ValueError: invalid literal for int() with base 10: 'weeble'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\azure\cli\main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "D:\Python35\lib\site-packages\azure\cli\core\application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "D:\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "D:\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 473, in _execute_command
    reraise(*sys.exc_info())
  File "D:\Python35\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "D:\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 450, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "D:\Python35\lib\site-packages\azure\cli\command_modules\batch_extensions\custom.py", line 142, in create_job
    expanded_job_object = template_utils.expand_template(template, parameters)
  File "D:\Python35\lib\site-packages\azure\cli\command_modules\batch_extensions\_template_utils.py", line 1038, in expand_template
    return _parse_template(json.dumps(template_json), template_json, parameters)
  File "D:\Python35\lib\site-packages\azure\cli\command_modules\batch_extensions\_template_utils.py", line 664, in _parse_template
    updated_json += _parse_template_string(string_content, template_obj, parameters)
  File "D:\Python35\lib\site-packages\azure\cli\command_modules\batch_extensions\_template_utils.py", line 613, in _parse_template_string
    parsed = _parse_arm_expression(expression, template_obj, parameters)
  File "D:\Python35\lib\site-packages\azure\cli\command_modules\batch_extensions\_template_utils.py", line 575, in _parse_arm_expression
    result = _parse_arm_parameter(expression[12:-2], template_obj, parameters)
  File "D:\Python35\lib\site-packages\azure\cli\command_modules\batch_extensions\_template_utils.py", line 510, in _parse_arm_parameter
    return _validate_int(user_value, param_def)
  File "D:\Python35\lib\site-packages\azure\cli\command_modules\batch_extensions\_template_utils.py", line 88, in _validate_int
    raise TypeError()
TypeError
```

It is very hard to locate the actual problem in all this traceback spew, and when you do it doesn't tell you which parameter was the culprit.

Ideally it should emit a message for _each_ parameter in error.

**Comment by annatisch** [comment]
This error has amended to be more informative, additionally error handling should now prevent stack traces being printed in the console in most circumstances.
