### ISSUE TITLE
Release is incompatible with CLI core version 2.0.20

### ISSUE THREAD

**Issue by dlepow** [Azure/azure-batch-cli-extensions#39]
Attempted to add extension to current CLI installation with:
az extension add --source https://github.com/Azure/azure-batch-cli-extensions/releases/download/azure-batch-cli-extensions-2.0.0/azure_batch_cli_extensions-2.0.0-py2.py3-none-any.whl

Error message:

The extension is not compatible with this version of the CLI.
You have CLI core version 2.0.20 and this extension requires a min of 2.0.17 and max of 2.0.18.

**Comment by hmeiland** [comment]
the message from HEAD seems worse: 
$ az extension add --source https://github.com/Azure/azure-batch-cli-extensions/releases/download/azure-batch-cli-extensions-2.0.0/azure_batch_cli_extensions-2.0.0-py2.py3-none-any.whl
Are you sure you want to install this extension? (y/n): y
No module named common
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/azure/cli/main.py", line 36, in main cmd_result = APPLICATION.execute(args)
File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/application.py", line 216, in execute result = expanded_arg.func(params)
File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 377, in __call__ return self.handler(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 631, in _execute_command except _load_azure_exception_class() as azure_exception:
File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 561, in _load_azure_exception_class from azure.common import AzureException ImportError: No module named common

this is on version: azure-cli (2.0.22.dev9299)

**Comment by xingwu1** [comment]
@dlepow and @cenit, released a new version. Please check it out.

**Comment by cenit** [comment]
thank you so much!! :)

**Comment by hmeiland** [comment]
works for me! thank you! you may want to put the url in the readme.MD:
az extension add --source https://github.com/Azure/azure-batch-cli-extensions/releases/download/azure-batch-cli-extensions-2.0.1/azure_batch_cli_extensions-2.0.1-py2.py3-none-any.whl
