### ISSUE TITLE
Extension relies on dependency not installed with the CLI

### ISSUE THREAD

**Issue by williexu** [Azure/azure-batch-cli-extensions#72]
The extension relies on this: https://pypi.org/project/azure-batch-extensions/
Leading to:
```
Unable to load extension 'azure-batch-cli-extensions'. Use --debug for more information.
Traceback (most recent call last):
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 176, in _update_command_table_from_extensions
    extension_command_table = _load_extension_command_loader(self, args, ext_mod)
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 582, in _load_extension_command_loader
    return _load_command_loader(loader, args, ext, '')
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 568, in _load_command_loader
    command_table = command_loader.load_command_table(args)
  File "C:\Users\wilx\.azure\cliextensions\azure-batch-cli-extensions\azext_batch\__init__.py", line 28, in load_command_table
    from azext_batch.commands import load_command_table
  File "C:\Users\wilx\.azure\cliextensions\azure-batch-cli-extensions\azext_batch\commands.py", line 12, in <module>
    from azure.batch_extensions import __version__ as batch_ext_version
ModuleNotFoundError: No module named 'azure.batch_extensions'
```

**Comment by xingwu1** [comment]
Update the batch extension to latest version:
https://github.com/Azure/azure-cli-extensions/pull/225
